SELECT
       PROCESS_ID,
       PROCESS_SUB_ID,
       PROCESS_TYPE,
       PROCESSOR,
       PROCESS_NAME,
       LEFT(LAST_PERIOD, 6) AS LAST_PERIOD,
       TRY_TO_TIMESTAMP_NTZ(LAST_DATE_PROCESSED) as LAST_PROCESSED_TS,
       TO_DATE(LAST_PROCESSED_TS) AS LAST_PROCESSED,
       DATEDIFF(DAY, LAST_PROCESSED, TO_DATE(CONVERT_TIMEZONE('UTC', 'America/New_York', CURRENT_TIMESTAMP()))) AS LAST_PROCESSED_DATE_LAG,
       PROCESS_FREQUENCY,
       PENDING_FLAG,
       PAYOUT,
       INCOME_REVENUE_TYPE,
       SEQ_GROUP
FROM PROD.STAGING_COBSQL.WAREHOUSE_CONSOLIDATED_FIN_PROCESS_CONTROL_LIST
ORDER BY PROCESSOR